### ISSUE TITLE
ImportError: cannot import name '_ServerRequestAdapter

### ISSUE THREAD

**Issue by ghost** [bdarnell/tornado_http2#1]
It appears that this is no longer part of the core tornado framework from what I can tell?

```python
from tornado.httpserver import HTTPServer, _HTTPRequestContext, _ServerRequestAdapter
ImportError: cannot import name '_ServerRequestAdapter'
```

Just wanted to try this package out, as I'm very vested in moving some infrastructure to HTTP/2, and I haven't found a great way to hook H2 into tornado that plays well with all the rest of the framework.

Pointers on this would be welcome!

**Comment by bdarnell** [comment]
Thanks for the report. I've made a fix that gets things mostly working with Tornado 4.5. There are a few issues remaining but I think they're generally issues with the tornado test suite than with the http2 support. 

I'd appreciate any feedback once you give it a try - as you can tell by the fact that you reported issue #1, this hasn't gotten a lot of usage yet :)
